project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Does NYC Metro Region Have a Home-job Balance?"
  site-url: "https://nyc_home-job_balance.github.io/quarto-website-template" 
  repo-url: https://github.com/YinanLi-15/MUSA550_LLC_Quarto 
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Yinan Li, 2023"

  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nickhand.dev
        text: "Personal Website"
      - icon: github
        href: https://github.com/MUSA-550-Fall-2023/
        text: "MUSA 550 GitHub"
      - icon: twitter
        href: https://twitter.com/nicholashand
        text: "Nick Hand Twitter"         

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/1_Data_Processing.ipynb 
          - analysis/2_LODES.ipynb
          - analysis/3_ACS.ipynb
          - analysis/4_MachineLearning.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




